/ ‘src/pssh2/pssh2_seq’

diff --git a/src/pssh2/pssh2_seq b/src/pssh2/pssh2_seq
--- a/src/pssh2/pssh2_seq
+++ b/src/pssh2/pssh2_seq
@@ -81,6 +81,7 @@ do
 	t) table_name=$OPTARG;;
 	h) usage; exit;;
 	s) silent=1; passOpt="$passOpt -$opt";;
+	:)  echo "Error: -$OPTARG requires an argument"; usage; exit 1;;
 	*) passOpt="$passOpt -$opt";;
 	esac
 done
